name: Atomic Sound L.L.C.
favicon: null
layout_spectrum: 0.3048
typography_spectrum: 0.64564
title: Atomic Sound L.L.C.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9375
  lightness: 0.25
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
